# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Project
    url: tour
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: News
    url: news
    weight: 30